{{ define "content" }}
<div class="py-5 text-center">
  <img class="d-block mx-auto mb-4" src="/assets/bootstrap-solid.svg" alt="" width="72" height="72">
  <h2>Publish Platform</h2>
  <p class="lead">This is an information Publish platform for SDUT Computer College Software Lab. The website is generated by a <a href="https://github.com/sdutsoftlab/softlab-generator">generator</a> which is developed by us.</p>
</div>

<div class="row">
  <div class="col-md-12 order-md-12 mb-12">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col" colspan="5">Title</th>
          <th scope="col" colspan="1" class="text-center">Date</th>
          <th scope="col" colspan="1" class="text-center">Author</th>
        </tr>
      </thead>
      <tbody>
        {{ range .artlist }}
            <tr>
              <td colspan="5">
                <a href="{{ .Url }}">{{ .Title }}</a>
              </td>
              <td colspan="1" class="text-center">{{ .CreatedAt | format }}</td>
              <td colspan="1" class="text-center">{{ .Author }}</td>
            </tr>
        {{ end }}
      </tbody>
    </table>
  </div>
</div>
{{ end }}